#Mybatis XML PATH
mybatis:
  mapperLocations: classpath:mapper/*.xml

#THYMELEAF CONFIG
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false